package com.xiaomaigou.mapper;

import com.xiaomaigou.pojo.TbBrand;
import com.xiaomaigou.pojo.TbBrandExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TbBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    long countByExample(TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int deleteByExample(TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int insert(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int insertSelective(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    List<TbBrand> selectByExample(TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    TbBrand selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbBrand record, @Param("example") TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int updateByExample(@Param("record") TbBrand record, @Param("example") TbBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int updateByPrimaryKeySelective(TbBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_brand
     *
     * @mbg.generated Wed Aug 15 20:26:13 CST 2018
     */
    int updateByPrimaryKey(TbBrand record);

    /**
     * 模板管理品牌下拉列表，select2要求格式必须为 { "id": 2, "text": "duplicate" }格式
     *
     * @return
     */
    List<Map> selectOptionList();
}